### ISSUE TITLE
Build error on windows: "assets/osu/shaders/slider.h" not found

### ISSUE THREAD

**Issue by dragsbruh** [FireRedz/kurarin#6]
I am on windows 11. I used the `-prod` flag, and have gcc in path.

```
builder error: Header file "assets/osu/shaders/slider.h", needed for module `core.osu.parsers.beatmap.object.graphic` was not found. Please install the corresponding development headers.
```
Probably you forgot to include it in the repo or is it a windows specific thing?

**Comment by xjunko** [comment]
You were supposed to use the [ext/build.sh](https://github.com/xjunko/kurarin/blob/rewrite/ext/build.sh) script to build the program, also it's linux only.

You can skip the script part by building the shader manually with `v shader assets/osu/shaders`, but there's nothing much I could do about the windows incompatibility because of the audio engine.
